### ISSUE TITLE
Works only with --foreground or --debug

### ISSUE THREAD

**Issue by kovvalsky** [mnencia/mchfuse#15]
Thank you for this project. I cloned and installed mchfuse.
It works when I execute with `--debug`: the directory appears in a file browser (nautilus) and also the directory is not empty.
```mchfuse --debug  -c .local/lib/mchfuse/mchfuse.conf "Cloudia" ~/Cloud```

When I run without `--debug`, keeping the rest of the command exactly the same, nothing is mounted. The directory is empty and the file browser doesn't show any new directory.
```mchfuse -c .local/lib/mchfuse/mchfuse.conf "Cloudia" ~/Cloud```

Any idea what might be stopping to mount the drive without debug mode?

Maybe the following is not relevant:
after I stop the connection with `Ctrl+C` the drive cannot be unmounted with `umount`, I use `fusermount -u`.

**Comment by kovvalsky** [comment]
The previous was on Ubuntu 16.04 (64 bit).
I also tried on 18.04 and the same issue: mounts only with `--debug`.

**Comment by matejmosko** [comment]
Thank for your work. It's same for me on ubuntu 20.04.

**Comment by mnencia** [comment]
The `--debug` flag should not change the behaviour of mchfuse; it only adds some output. But it also implies the `--foreground` flag, to remain attached to the current terminal. 

Could you please check if using `--foreground` by itself fixes your issue?

**Comment by kovvalsky** [comment]
`--foreground` flag does mount the drive like `--debug` but, of course, without printing logs.

**Comment by rzeigler** [comment]
It doesn't appear to be connecting to a tty directly that is the critical fact.

I can happily launch with -f while backgrounding the process and piping output to /dev/null and I still get a successful mount.

**Comment by mnencia** [comment]
Could you please try with the latest version? It now closes the descriptors when going background, and that should fix the issue.

**Comment by rzeigler** [comment]
So following `git pull` and rebuild the behavior seems unchanged.

**Comment by mnencia** [comment]
This is surely a bug, but I'm not able to reproduce it. If you could give me any hint about what could be the difference between my systems and yours I'd be grateful. However, I'll try again during the weekend to reproduce your setup and debug this issue.

**Comment by mantielero** [comment]
Same issue here with ArchLinux

**Comment by mnencia** [comment]
I've not been able to reproduce, but I'm sure that the issue is in the way mchfuse demonize itself. 

Could you please try using the godaemon branch 1404bbf907f3cba70086d8e7f8368ee5fe36e899 to see if daemonizing using a well-known library fixes your issue?

**Comment by mantielero** [comment]
That solved the issue for me.
