### ISSUE TITLE
Can't connect: status code 401

### ISSUE THREAD

**Issue by matejmosko** [mnencia/mchfuse#17]
Today I wanted to access the company disk from my home office, but this error has displayed instead of any mounting.

`2020/10/15 14:44:39 Failure signing in My Cloud Home account: status code 401 logging in on https://prod1.mycloud.com/authrouter/oauth/token: unexpected status code
`

**Comment by cyberdive** [comment]
Hello matejmosko,
Just to tell you that's the first time I try to use this tool, and I get the same error. I'll investigate if I can help.
Is it the first time that you connect to your WD with this tool ?
I tried to put the credential in the config file and directly in the command line, same error.
Br,
Patrick

**Comment by cyberdive** [comment]
I tried also --debug, with no luck...

**Comment by cyberdive** [comment]
Hello,
small info, I created a vm in linode (cloud provider) and tried the procedure : 
curl -sSfL https://github.com/mnencia/mchfuse/raw/master/install.sh | sudo sh -s -- -b /usr/local/bin

cat > mchfuse.conf << 'EOF'
username = "LOGIN" //of course updated
password = "PSW" //of course updated
EOF

mkdir /mnt/t
chmod 600 mchfuse.conf
mchfuse -c mchfuse.conf DEVICE_NAME /mnt/t

same result : 
2020/10/25 19:43:04 Failure signing in My Cloud Home account: status code 401 logging in on https://prod1.mycloud.com/authrouter/oauth/token: unexpected status code

Any idea ? Any help is welcome ;-)

Br,

Patric;k

**Comment by mnencia** [comment]
Same for me. They changed something in the API. I'm investigating.

**Comment by cyberdive** [comment]
Hello mnencia, 

First thank you for the work you have done, and also for your quick answer.

I was looking to theses documentation (that you know) to see if I can troubleshoot.

https://developer.westerndigital.com/develop/wd-my-cloud-home/api/endpoint/get--v1-config.html
https://developer.westerndigital.com/develop/wd-my-cloud-home/api/authentication/get--v2-auth0-user.html

I'm too tired tonight but I'll try to have a look if I can find some thing (just trying to help) tomorrow.

Have a good day

Patrick

**Comment by mshavliuk** [comment]
Any news?

**Comment by bibi-blocksberg** [comment]
can u please fix the api error  bro

**Comment by mnencia** [comment]
I should have fixed it. Unfortunately, the method I've used before to obtain an auth0 client_id is not working anymore. So I had to include a client_id/client_secret pair inside the code. I do not like it, but it is the only way I've found.

I'm going to do a new release this evening, after reviewing the other open issues.
