### ISSUE TITLE
Operation not supported

### ISSUE THREAD

**Issue by Tester2009** [mnencia/mchfuse#18]
Hello there.

I am finally able to use this mchfuse on my Ubuntu 18.04 with a compiled version. The binary version seems to have an error which `status code 401`. You may want to check that one line bash script. But that not the case here since I can compile it.

The issue here is when I try to modify/edit the file in my drive, I got an error such as `Operation not supported`. The simple one is I use nano to edit the file inside that drive and got the error.

The other one is, I cannot open any files in that drive. I have set the directory permission with my username and group, and run mchfuse as my user, not root.

Can you check why this happened? I'm very happy to see this project. Thank you for your good work!

**Comment by DocBlack89** [comment]
Hey ! 

I've the same problem with the release version. 
mchfuse is launch with --allow-other flag.
There is the log when I try to cat a txt file (4ko) of my cloudhome : 

`2020/11/23 10:30:53 rx 254: STATFS i1 
2020/11/23 10:30:53 tx 254:     OK, {blocks (0,0)/0 files 0/0 bs0 nl0 frs0}
2020/11/23 10:30:54 rx 256: STATFS i1 
2020/11/23 10:30:54 tx 256:     OK, {blocks (0,0)/0 files 0/0 bs0 nl0 frs0}
2020/11/23 10:30:55 rx 258: OPENDIR i9223372036854775812 
2020/11/23 10:30:55 tx 258:     OK, {Fh 1 }
2020/11/23 10:30:55 rx 260: GETATTR i9223372036854775812 {Fh 0} 
2020/11/23 10:30:55 tx 260:     OK, {tA=1s {M040755 SZ=0 L=0 0:0 B0*4096 i0:9223372036854775812 A 1605780157.361000 M 1605780157.361000 C 1591301301.000000}}
2020/11/23 10:30:55 rx 262: READDIRPLUS i9223372036854775812 {Fh 1 [0 +4096)  L 0 LARGEFILE,NONBLOCK,DIRECTORY} 
2020/11/23 10:30:55 tx 262:     OK,  4072b data "+\x00\x00\x00\x00\x00\x00\x80"...
2020/11/23 10:30:55 rx 264: READDIRPLUS i9223372036854775812 {Fh 1 [24 +4096)  L 0 DIRECTORY,NONBLOCK,LARGEFILE} 
2020/11/23 10:30:55 tx 264:     OK,  3960b data "\x1b\x00\x00\x00\x00\x00\x00\x80"...
2020/11/23 10:30:55 rx 266: READDIRPLUS i9223372036854775812 {Fh 1 [47 +4096)  L 0 LARGEFILE,NONBLOCK,DIRECTORY} 
2020/11/23 10:30:55 tx 266:     OK,  336b data "\x13\x00\x00\x00\x00\x00\x00\x80"...
2020/11/23 10:30:55 rx 268: READDIRPLUS i9223372036854775812 {Fh 1 [49 +4096)  L 0 DIRECTORY,NONBLOCK,LARGEFILE} 
2020/11/23 10:30:55 tx 268:     OK
2020/11/23 10:30:55 rx 270: RELEASEDIR i9223372036854775812 {Fh 1 NONBLOCK,LARGEFILE,DIRECTORY  L0} 
2020/11/23 10:30:55 tx 270:     OK
2020/11/23 10:30:55 rx 272: OPEN i9223372036854775828 {LARGEFILE} 
2020/11/23 10:30:55 tx 272:     OK, {Fh 1 }
2020/11/23 10:30:55 rx 274: READ i9223372036854775828 {Fh 1 [0 +4096)  L 0 LARGEFILE} 
2020/11/23 10:30:55 tx 274:     95=operation not supported
2020/11/23 10:30:55 rx 276: READ i9223372036854775828 {Fh 1 [0 +4096)  L 0 LARGEFILE} 
2020/11/23 10:30:55 tx 276:     95=operation not supported
2020/11/23 10:30:55 rx 278: FLUSH i9223372036854775828 {Fh 1} 
2020/11/23 10:30:55 tx 278:     OK
2020/11/23 10:30:55 rx 280: RELEASE i9223372036854775828 {Fh 1 LARGEFILE  L0} 
2020/11/23 10:30:55 tx 280:     OK
2020/11/23 10:30:55 rx 282: STATFS i1 
2020/11/23 10:30:55 tx 282:     OK, {blocks (0,0)/0 files 0/0 bs0 nl0 frs0}`

Hope it can helpl !

**Comment by mnencia** [comment]
Thanks for the log. It will be useful understand what is happening.

**Comment by digodugo** [comment]
Hello Marco, same issue for me.
Actually WD is mounted and I can mkdir inside mounted MyCloud but I'm not able to move a file inside. Copying (cp ex.jpg /mnt/prova/Mycloud) a .jpg file, report that is not "able to create regular file" but inside portal-MyCloud I see the file but zero size.
If I copy again the file reports "Operation not supported".

Furthermore, why folder where I decided to mount WD (/mnt/prova/Mycloud) is not showed as a folder by "ls" ?
Root folder (/mnt/prova/) is shared with SAMBA but trying to view inside with another device I'm able to see "Mycloud" as a file with zero size. Seems that mchfuse create only a virtual folder.

(In pratica nonostate sia in grado di vedere il contenuto del WD, non sono in grado di copiarci dentro un file. All'inizio riporta che non è in grado di creare un file "regular" mentre se riprovo mi dice che l'operazione non è consentita. Nonostante gli errori, dal portale Mycloud io vedo il file che avevo provato a copiare ma ha una dimenzione nulla. Inoltre non riesco a capire perchè la cartella dove è stato montato il WD non è vista come tale e SAMBA non riesce a condividerla come una semplice cartella)

**Comment by mnencia** [comment]
This is really interesting. I've been able to reproduce it. The log is:

```
2020/12/09 12:19:28 rx 64: GETATTR i1 {Fh 0}
2020/12/09 12:19:28 tx 64:     OK, {tA=1s {M040755 SZ=0 L=0 1000:1000 B0*4096 i0:1 A 1607512760.235000 M 1607512760.235000 C 1586266208.800000}}
2020/12/09 12:19:28 rx 66: LOOKUP i1 ["x.txt"] 6b
2020/12/09 12:19:28 tx 66:     2=no such file or directory, {i0 g0 tE=0s tA=0s {M00 SZ=0 L=0 0:0 B0*0 i0:0 A 0.000000 M 0.000000 C 0.000000}}
2020/12/09 12:19:28 rx 68: LOOKUP i1 ["x.txt"] 6b
2020/12/09 12:19:28 tx 68:     2=no such file or directory, {i0 g0 tE=0s tA=0s {M00 SZ=0 L=0 0:0 B0*0 i0:0 A 0.000000 M 0.000000 C 0.000000}}
2020/12/09 12:19:28 rx 70: LOOKUP i1 ["x.txt"] 6b
2020/12/09 12:19:28 tx 70:     2=no such file or directory, {i0 g0 tE=0s tA=0s {M00 SZ=0 L=0 0:0 B0*0 i0:0 A 0.000000 M 0.000000 C 0.000000}}
2020/12/09 12:19:28 rx 72: CREATE i1 {0100600 [WRONLY,CREAT,EXCL,0x8000] (022)} ["x.txt"] 6b
2020/12/09 12:19:28 tx 72:     OK, {i9223372036854775813 g0 {M0100644 SZ=0 L=0 1000:1000 B0*4096 i0:9223372036854775813 A 1607512768.562000 M 1607512768.562000 C 1607512768.562000} &{1 0 0}}
2020/12/09 12:19:28 rx 74: WRITE i9223372036854775813 {Fh 1 [0 +5)  L 0 WRONLY,0x8000}  5b
2020/12/09 12:19:28 tx 74:     95=operation not supported
2020/12/09 12:19:28 rx 76: FLUSH i9223372036854775813 {Fh 1}
2020/12/09 12:19:28 tx 76:     OK
2020/12/09 12:19:28 rx 78: RELEASE i9223372036854775813 {Fh 1 WRONLY,0x8000  L0}
2020/12/09 12:19:28 tx 78:     OK
```

I'll try to debug it.
