### ISSUE TITLE
Nice work!

### ISSUE THREAD

**Issue by scottfriz** [mnencia/mchfuse#2]
Nice work, my friend!
I got this working with a My Cloud Home Duo on Ubuntu 20.04.
I just need to get a permission issue worked out when trying to browse the file system, but other than that it's working well.

Thanks for your effort.
Scott

**Comment by mnencia** [comment]
I'm glad you find it useful. If you describe your issue I could try to help you, and then I'll update the documentation to help others.

**Comment by scottfriz** [comment]
Once the MyCloud is mounted, I can only access it if I launch the file manager as root. 
Under standard user, I get ['Could not display "/media/scott/MyCloud"  "The location is not a folder"] when mounted under File System.
Or ["The folder contents could not be displayed" " You do not have the permissions necessary to view the contents"] when mounted in my home directory.
In both cases it's fine when I open as root.

**Comment by mnencia** [comment]
By default all fuse filesystems are accessibile only by the user that mounted them. You can use the `--allow-other` flag to enable other users to access the mchfuse mountpoint.
