### ISSUE TITLE
Failure signing in My Cloud Home account: status code 429

### ISSUE THREAD

**Issue by fga74fr** [mnencia/mchfuse#27]
Hello,

MCHFuse was installed using the pre-built binary on an aarch64 machine running Ubuntu 20.04.2.

I get the following error message "Failure signing in My Cloud Home account: status code 429 logging in on https://prod.wdckeystone.com/authrouter/oauth/token: unexpected status code"

I double checked the username and password which are working well on https://home.mycloud.com and tried using a configuration file or passing username and password in the command line always getting the same error.

Debug option didn't gave any additional information. 

Any help would be greatly appreciated, please let me know if any more information is necessary to understand what is going wrong.

Best regards

Francois

**Comment by mnencia** [comment]
Hi, 

I've tried to reproduce this issue, but without success. My guess is that some network apparate or software in your setup is messing up with the authentication calls. Can you try accessing using a different network connection?

**Comment by fga74fr** [comment]
Hello,

Thank you for your answer. The issue was related to the network and more precisely to the way my ISP handles the public IPv4 adresses provided to customers. By default they provide a fixed IPv4 shared between 4 customers. One of the consequences of this setup is that the IPv4 address can be changed when two of the customers sharing the same IPv4 address try to use the same port. A dedicated public IPv4 address can be provided and this seem to solve the problem.

With this new network setup, the disk is correctly mounted and everything seems to work well.

Thank you for providing this _very_ helpfull software !!!

Best regards

Francois
