### ISSUE TITLE
Usage Guide

### ISSUE THREAD

**Issue by raven2cz** [mnencia/mchfuse#3]
Hello!
Is it possible with your lib direct access to WD My Cloud Home from linux?
If yes, can you describe small user guide? Your notes are good, but I don't know where can I get user name and password, etc. Because I have just email and password to web cloud app and to WD Discovery app. 
Can I use IP address instead of DEVICE_NAME? And which dir destination can I used in the command, root or some "volume" dir? 
I need more information for successful usage of your lib, thanks!  I'm waitint to this possibility almost 2 years!!!

**Comment by mnencia** [comment]
Hi,

> Hello!
> Is it possible with your lib direct access to WD My Cloud Home from linux?

Yes, it is possible.

> If yes, can you describe small user guide? Your notes are good, but I don't know where can I get user name and password, etc. Because I have just email and password to web cloud app and to WD Discovery app.

The email and the password are exactly your credentials you need to use.

> Can I use IP address instead of DEVICE_NAME? 

No, it is not possible. It needs to discover the device using the cloud service. At the moment mchfuse uses only the local IP (that it discovers from the cloud service), but I'm working to allow the usage of your cloud device also from outside the device LAN. However, if you put the wrong device name, the error message will tell you the list of the available devices.

> And which dir destination can I used in the command, root or some "volume" dir?

You can specify both a source directory inside the device and a mountpoint anywhere in your Linux machine filesystem hierarchy. 

> I need more information for successful usage of your lib, thanks! I'm waitint to this possibility almost 2 years!!!

I'm also working to improve the documentation, thanks for the feedback.
