### ISSUE TITLE
Cloud source directory

### ISSUE THREAD

**Issue by raven2cz** [mnencia/mchfuse#4]
Hello,
I already access to my cloud home. It seems that the user/pass and deviceName works!
But I don't know how to find correct cloud home source directory which is required. How can I find this path? For example I have standard records in the plex directory which is installed on the device in plex folder. But I expect that it is not directly in the root folder, there can be much more complex path. But I cannot find the full directory structure.

**Comment by mnencia** [comment]
Hi,
the directory path after the deviceName is totally optional, if you do not specify a directory you mount the root of the device, and you have access to the whole filesystem.

The rationale of specifying a path is to restrict what is accessible from the Linux mount, but it is perfectly fine to leave it empty.

Could you please give me an example of what you are trying to achieve?

**Comment by raven2cz** [comment]
I tried:
sudo mchfuse -u MYEMAIL -p MYPASS CloudHome /home/box/cloud
But nothing happened. The cli is frozen and no output, the processing is in some loop or waiting. If I set wrong cloud name, there is correct error message, and write correct name of cloud. So, the access and cloud name discovery works. But the access to the cloud is frozen.

**Comment by raven2cz** [comment]
All works! Thanks! I do not start mchfuse in background with & 
So the console was frozen and I don't know that it is correctly mounted. It is important to know that it has to be background process. Sorry.
