### ISSUE TITLE
Possible way to compile mchfuse for raspi ARM.

### ISSUE THREAD

**Issue by raven2cz** [mnencia/mchfuse#5]
Is it possible to compile your GO lang code for raspi ARM processors?

I tried it on raspi 4, but I've got error:
mch/client.go:82: Errorf format %w has unknown verb w
mch/client.go:128: Errorf format %w has unknown verb w
mch/client.go:209: Errorf format %w has unknown verb w
mch/device.go:111: Errorf format %w has unknown verb w
mch/device.go:171: Errorf format %w has unknown verb w
mch/device.go:220: Errorf format %w has unknown verb w
mch/device.go:264: Errorf format %w has unknown verb w
mch/device.go:275: Errorf format %w has unknown verb w
mch/files.go:63: Errorf format %w has unknown verb w
mch/files.go:90: Errorf format %w has unknown verb w
mch/files.go:135: Errorf format %w has unknown verb w
mch/files.go:161: Errorf format %w has unknown verb w
mch/files.go:231: Errorf format %w has unknown verb w
mch/files.go:249: Errorf format %w has unknown verb w
mch/files.go:278: Errorf format %w has unknown verb w
mch/files.go:333: Errorf format %w has unknown verb w
mch/files.go:372: Errorf format %w has unknown verb w
mch/files.go:408: Errorf format %w has unknown verb w
mch/files.go:429: Errorf format %w has unknown verb w

github.com/mnencia/mchfuse/fsnode
fsnode/fsnode.go:166: Errorf format %w has unknown verb w

Go was correctly installed on the raspi.

**Comment by mnencia** [comment]
What version of go you are using? The %w verb was added in go 1.13.

**Comment by mnencia** [comment]
I see that Raspbian Buster ships go 1.11. You can try installing the latest version following the instructions at https://www.e-tinkers.com/2019/06/better-way-to-install-golang-go-on-raspberry-pi/ or cross-compile it on a different machine that has a more recent go.

The following command should generate an executable compatible with any Raspberry around:

```bash
GOOS=linux GOARCH=arm GOARM=5 make
```

**Comment by mnencia** [comment]
I've added a precompiled binary for Raspberry PI (tested on 2, 3 and 4) the latest release. You can install it using the instructions at <https://github.com/mnencia/mchfuse#installing-the-latest-release>

**Comment by raven2cz** [comment]
Works thanks!!!
