### ISSUE TITLE
 init: 19=operation not supported by device

### ISSUE THREAD

**Issue by gdemarchi** [mnencia/mchfuse#6]
Hi Marco,
I'm on mac, I managed to download and compile the mchfuse binary, but when i try to connect from the command line:

sudo ./mchfuse -u my.name@gmail.com -p "mypassword" "My Own Cloud Home Duo" /Users/myuser/tmpmnt/ -d

I get 

 19=operation not supported by device

User/pwd should be correct, because at first I put the wrong one and it was correctly telling me which one was available ... any hint?! I tried also without sudo, same outcome ...
Thanks and best,
-g

**Comment by mnencia** [comment]
Hi Giampaolo,

it looks like mchfuse is not able to speak with the `osxfuse` extension. 

What version of OSX you have? What version of `osxfuse`?

I've just realized that I do not mention in the readme that `osxfuse` is required to run mchfuse on OSX. You can install it using homebrew with the following command:

```
brew cask install osxfuse
```

**Comment by gdemarchi** [comment]
Pfff ... I wrote quite and extensive email but Mail crashed and no draft, grrr :(
Let's do it shorter and online :)
1) Yes, highlight the need of osxfuse for Mac users, despite the hint in the name "mch**fuse**"
2) Indeed, upgrading to 10.15.5 (I was on the publica beta) but mainly reinstalling osxfuse did the trick. I had probably quite an old version of osxfuse lingering around, I trigged brew to reinstall it, and eventually worked ...

Thanks, IMHO you we can close it ...
Best,
-g
