### ISSUE TITLE
Fail to login ubuntu 20.04

### ISSUE THREAD

**Issue by dr3mro** [mnencia/mchfuse#8]
I tried to login using both compile from source and  latest release and I get errors as follows
 ./mchfuse  -c mchfuse.conf NetStorage ~/mch/ns/
2020/06/07 19:41:14 Failure signing in My Cloud Home account: Post "https://wdc.auth0.com/oauth/token": net/http: TLS handshake timeout
my username and passowrd contains numbers ans letters and i had to encapulate both in "" to force mcfuse to accept it or it will complain of username and password

**Comment by mnencia** [comment]
That kind of error suggests some, hopefully temporary, network issue. Could you try again from a different network connection?

**Comment by dr3mro** [comment]
yeah .. it works ... but seems to be alpha stage now .. I hope to see it mature soon .. That is the only reason I still use windows and not linux till now 
Thanks for the good job

**Comment by dr3mro** [comment]
it works with ethernet but with wifi it don't work can we change the timeout ??

**Comment by mnencia** [comment]
Raising the timeout could be a solution only if the other part is going to answer after some time. Could you please try to execute the mchfuse with `GODEBUG=http2debug=1` in the environment?

```
export GODEBUG=http2debug=1 
```

I should print a lot of information about the authentication calls only as Auth0 servers speak http2 while the MCH NAS doesn't. 

> **WARNING**:  Please check the output for credentials before attacking to the ticket.

**Comment by dr3mro** [comment]
It works on ethernet so Iam sure my creditials are ok but is it safe to post the debug here?
does it contain any sensitive data like usernames or passwords or ip addresses ?

**Comment by mnencia** [comment]
I just checked, it contains several sensitive pieces of information, so it is better to not attach it directly.

```
2020/06/08 14:18:43 http2: Transport failed to get client conn for config.mycloud.com:443: http2: no cached connection was available
2020/06/08 14:18:43 http2: Transport creating client conn 0xc000001680 to 13.226.173.37:443
2020/06/08 14:18:43 http2: Transport encoding header ":authority" = "config.mycloud.com"
2020/06/08 14:18:43 http2: Transport encoding header ":method" = "GET"
2020/06/08 14:18:43 http2: Transport encoding header ":path" = "/config/v1/config"
2020/06/08 14:18:43 http2: Transport encoding header ":scheme" = "https"
2020/06/08 14:18:43 http2: Transport encoding header "accept-encoding" = "gzip"
2020/06/08 14:18:43 http2: Transport encoding header "user-agent" = "Go-http-client/2.0"
2020/06/08 14:18:43 http2: Transport received SETTINGS len=18, settings: MAX_CONCURRENT_STREAMS=128, INITIAL_WINDOW_SIZE=65536, MAX_FRAME_SIZE=16777215
2020/06/08 14:18:43 http2: Transport received WINDOW_UPDATE len=4 (conn) incr=2147418112
2020/06/08 14:18:43 http2: Transport received SETTINGS flags=ACK len=0
2020/06/08 14:18:43 http2: Transport received HEADERS flags=END_HEADERS stream=1 len=300
2020/06/08 14:18:43 http2: Transport received DATA stream=1 len=8192 data="{\n  \"data\": {\n    \"configurationId\": \"global_default\",\n    \"componentMap\": {\n      \"com.wd.portal\": {\n        \"portal.auth0.client\": \"SGqemVDDxd20pufijh4mzkzu017ZBpN9\"\n      },\n      \"com.wd.device\": {\n        \"p2p_enabled\": false,\n        \"restore_config\"" (7936 bytes omitted)
2020/06/08 14:18:43 http2: Transport received DATA stream=1 len=1761 data="\"https://collectors.us2.sumologic.com/receiver/v1/http/ZaVnC4dhaV1dwuoPhmo2rIWW09XUfap6qw6OqmUy714Q5NwC1SFJIQrKcbsY34bM3aIDOPFeKY304QmzUMMuzkiijOQjfbg2qObJDO_XEi8sqLp_ZnEgnQ==\",\n        \"analytics.device.WDMyCloudDL4100.url\": \"https://collectors.us2.sumolo" (1505 bytes omitted)
2020/06/08 14:18:43 http2: Transport received DATA flags=END_STREAM stream=1 len=0 data=""
2020/06/08 14:18:43 http2: Transport failed to get client conn for wdc.auth0.com:443: http2: no cached connection was available
2020/06/08 14:18:44 http2: Transport creating client conn 0xc000702900 to 54.185.227.32:443
2020/06/08 14:18:44 http2: Transport encoding header ":authority" = "wdc.auth0.com"
2020/06/08 14:18:44 http2: Transport encoding header ":method" = "POST"
2020/06/08 14:18:44 http2: Transport encoding header ":path" = "/oauth/token"
2020/06/08 14:18:44 http2: Transport encoding header ":scheme" = "https"
2020/06/08 14:18:44 http2: Transport encoding header "content-type" = "application/json"
2020/06/08 14:18:44 http2: Transport encoding header "content-length" = "324"
2020/06/08 14:18:44 http2: Transport received SETTINGS len=18, settings: MAX_CONCURRENT_STREAMS=128, INITIAL_WINDOW_SIZE=65536, MAX_FRAME_SIZE=16777215
2020/06/08 14:18:44 http2: Transport encoding header "accept-encoding" = "gzip"
2020/06/08 14:18:44 http2: Transport encoding header "user-agent" = "Go-http-client/2.0"
2020/06/08 14:18:44 http2: Transport received WINDOW_UPDATE len=4 (conn) incr=2147418112
2020/06/08 14:18:44 http2: Transport received SETTINGS flags=ACK len=0
2020/06/08 14:18:44 http2: Transport received HEADERS flags=END_HEADERS stream=1 len=696
2020/06/08 14:18:44 http2: Transport received DATA stream=1 len=1497 data="***REDACTED***" (1241 bytes omitted)
2020/06/08 14:18:44 http2: Transport received DATA flags=END_STREAM stream=1 len=0 data=""
```

This is my log until the point where it fails for you. I've redacted the last "Transport received DATA stream" line that contains AUTH tokens that are sensitive.

**Comment by dr3mro** [comment]
I think think if there is a connection issue with internet like dropped packets in case of wifi or dns issues it will fail and that does not happen if I use ethernet or I did restart my router .. 
can you create update that gives safe debug info ? As this is much insecure and can give some rog person access to my whole data

**Comment by mnencia** [comment]
I've researched a bit, but I have not found any straightway to redact the sensitive information in the HTTP2 debug trace. Given that you solved the network issue, I'm going to close this issue.
